"""Per-pair contact significance: calibrated tests, FDR control, and null calibration.

Public API: `test_contacts` (recompute per-pair p-values under a named null
and attach BH-adjusted q-values), `read_local_decay_calls` (load either
output layout of `touche local-decay call` into a frame `test_contacts`
accepts), and `assess_calibration` (check whether a p-value column is
actually uniform under the null, stratified by distance or coverage).

Why this module exists: the reference workflow's Fisher score is retained
under the name `legacy_fisher` for exact reproducibility, but its 2x2 table
is not generated by the contact-sampling process (see
`touche.metadata.METHOD_REGISTRY`), so adjusting it for multiplicity cannot
make it a calibrated discovery set. `method="binomial"` uses the trial total
and null probability the local-decay model already computes, which is a null
the data can actually be checked against -- and `assess_calibration` is how
you check it before quoting `q < 0.05`.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import polars as pl

from touche.local_decay import (
    LOCAL_DECAY_OUTPUT_COLUMNS,
    SIGNIFICANCE_METHODS,
    TIDY_LOCAL_DECAY_COLUMNS,
    to_tidy_calls,
)
from touche.metadata import MethodInfo, StatResult, method_info
from touche.stats import ADJUST_METHODS, adjust_pvalue_column, binom_sf_greater, fisher_greater_batch, poisson_sf_greater

DEFAULT_ALPHA_LEVELS = (0.001, 0.01, 0.05, 0.1)


def test_contacts(
    calls: pl.DataFrame,
    *,
    method: str = "binomial",
    fdr: str = "bh",
    fdr_scope: str | list[str] | None = None,
    recompute: bool = True,
    fisher_backend: str = "numba",
    decay_model: str | None = None,
) -> StatResult:
    """Test each called pair under `method` and attach multiplicity-adjusted q-values.

    `calls` is a tidy `touche local-decay call` frame (see
    `read_local_decay_calls`). `recompute=False` keeps the `p_value` already
    in the frame and only applies FDR, which is what `call_local_decay` uses
    since it has just computed the p-values itself.

    `fdr_scope=None` declares one global family over every row of `calls` --
    the meaning a bare `q_value` carries. Passing column names stratifies the
    family; that is only valid if the strata were fixed before looking at the
    p-values, and the choice is recorded in the returned metadata either way.

    Pairs with no trials (`n_trials == 0`) are untestable rather than
    non-significant: their `p_value` and `q_value` are null, and they are
    excluded from the family size so they cannot dilute the correction.
    """

    if method not in SIGNIFICANCE_METHODS:
        raise ValueError(f"method must be one of: {', '.join(sorted(SIGNIFICANCE_METHODS))}")
    if fdr not in ADJUST_METHODS:
        raise ValueError(f"fdr must be one of: {', '.join(sorted(ADJUST_METHODS))}")

    table = calls
    warnings: list[str] = []
    if recompute:
        table = _recompute_p_values(table, method=method, fisher_backend=fisher_backend)
    elif "p_value" not in table.columns:
        raise ValueError("recompute=False requires an existing p_value column")

    table = table.with_columns(pl.lit(method).alias("method"))
    table = adjust_pvalue_column(table, p_col="p_value", q_col="q_value", method=fdr, groupby=fdr_scope)

    info = contact_method_info(
        table,
        method=method,
        fdr=fdr,
        fdr_scope=fdr_scope,
        recompute=recompute,
        fisher_backend=fisher_backend,
        decay_model=decay_model,
        extra_warnings=warnings,
    )
    # q_value belongs next to the p_value it adjusts, not appended after the
    # provenance columns, so the two are read together.
    ordered = [c for c in TIDY_LOCAL_DECAY_COLUMNS if c in table.columns]
    ordered.insert(ordered.index("p_value") + 1, "q_value")
    rest = [c for c in table.columns if c not in ordered]
    return StatResult(table=table.select([*ordered, *rest]), info=info)


def contact_method_info(
    calls: pl.DataFrame,
    *,
    method: str,
    fdr: str | None = None,
    fdr_scope: str | list[str] | None = None,
    recompute: bool = True,
    fisher_backend: str = "numba",
    decay_model: str | None = None,
    extra_warnings: list[str] | None = None,
) -> MethodInfo:
    """Describe a per-pair significance run: counts, FDR family, and assumption warnings.

    Shared by `test_contacts` and by `call_local_decay`'s legacy-layout path.
    The reference nine-column output has no header and no `q_value` column,
    so when it is written under a non-default null its sidecar is the only
    record of which null produced column five. Pass `fdr=None` for that case,
    where no correction was applied.
    """

    warnings = list(extra_warnings or [])
    if decay_model == "legacy" and method != "legacy_fisher":
        warnings.append(
            "decay_model='legacy' reproduces the reference background model including its scale "
            "error, so expected counts are roughly half what they should be and this test rejects "
            "several times more often than its nominal level. Treat q_value as a ranking, not as "
            "an FDR-controlled discovery set. Use decay_model='normalized' for calibrated "
            "p-values; see docs/statistics.md."
        )
    n_input = calls.height
    n_tested = int(calls["p_value"].is_finite().sum()) if n_input and "p_value" in calls.columns else 0
    untestable = n_input - n_tested
    if method == "legacy_fisher":
        warnings.append(
            "legacy_fisher is retained for reproducibility of the reference workflow. Its null "
            "is not the contact-sampling process, so its p-values are not calibrated and any "
            "derived q_value must not be reported as an FDR-controlled discovery set."
        )
    if untestable:
        warnings.append(
            f"{untestable} of {n_input} pairs were untestable under {method} (no trials or no "
            "expectation) and carry a null p-value; they are excluded from the FDR family."
        )
    if "n_trials" in calls.columns and n_input:
        median_trials = float(np.nanmedian(calls["n_trials"].cast(pl.Float64).to_numpy()))
        if median_trials < 10:
            warnings.append(
                f"Median n_trials is {median_trials:g}; discrete upper-tail p-values are coarse at "
                "this depth and the achievable minimum p-value may exceed the chosen alpha."
            )
    return method_info(
        method,
        alternative="greater",
        n_input=n_input,
        n_tested=n_tested,
        fdr_method=fdr,
        fdr_family=(
            None
            if fdr is None
            else "all called pairs"
            if fdr_scope is None
            else f"stratified by {fdr_scope}"
        ),
        filtered={"untestable": untestable},
        warnings=warnings,
        parameters={
            "recompute": recompute,
            "fisher_backend": fisher_backend if method == "legacy_fisher" else None,
            "decay_model": decay_model,
        },
    )


# `test_contacts` is an analysis entry point, not a unit test. Marking it here
# means importing it into a pytest module does not get it collected and run as
# a test with a missing `calls` fixture.
test_contacts.__test__ = False  # type: ignore[attr-defined]


def read_local_decay_calls(path: str | Path) -> pl.DataFrame:
    """Read either `touche local-decay call` output layout into a tidy frame.

    Detects the headerless nine-column reference layout by its lack of a
    `pair_id` header and promotes it onto the canonical pair schema. A legacy
    file carries no `n_trials`/`p_null`, so the columns exist but are null,
    and `test_contacts(method="binomial")` on it raises rather than silently
    testing against a fabricated trial total -- recall `local-decay call`
    with `--schema tidy` to get them.
    """

    path = Path(path)
    head = pl.read_csv(path, separator="\t", n_rows=1, has_header=True, infer_schema_length=0)
    if "pair_id" in head.columns:
        return pl.read_csv(path, separator="\t")
    legacy = pl.read_csv(path, separator="\t", has_header=False, new_columns=LOCAL_DECAY_OUTPUT_COLUMNS)
    legacy = legacy.with_columns(
        pl.lit(None, dtype=pl.Int64).alias("n_trials"),
        pl.lit(None, dtype=pl.Float64).alias("p_null"),
    )
    return to_tidy_calls(legacy, method="legacy_fisher")


def assess_calibration(
    table: pl.DataFrame,
    *,
    p_col: str = "p_value",
    strata: str | list[str] | None = None,
    alpha_levels: tuple[float, ...] = DEFAULT_ALPHA_LEVELS,
) -> pl.DataFrame:
    """Check whether a p-value column behaves like a null p-value column.

    Under a correctly specified null, p-values are uniform on `[0, 1]` and
    the fraction below any nominal alpha equals that alpha. This returns, per
    stratum, the number tested, a one-sample Kolmogorov-Smirnov test against
    `Uniform(0, 1)`, and the empirical rejection rate at each level in
    `alpha_levels`. Stratify by distance or coverage bins (`strata`) --
    a method can look uniform overall while being badly anticonservative for
    short-range or low-coverage pairs, which are exactly the pairs of
    interest.

    Run this on pairs drawn from a null set (distance- and coverage-matched
    shifted or random pairs), not on real enhancer-promoter pairs: real pairs
    are not expected to be null, so non-uniformity there is signal, not
    miscalibration.
    """

    if p_col not in table.columns:
        raise ValueError(f"{p_col!r} is not a column of the input table")
    keys = [] if strata is None else ([strata] if isinstance(strata, str) else list(strata))
    if keys:
        groups = [(dict(zip(keys, key)), part) for key, part in table.group_by(keys, maintain_order=True)]
    else:
        groups = [({}, table)]
    rows = [{**labels, **_calibration_row(part[p_col].to_numpy(), alpha_levels)} for labels, part in groups]
    return pl.DataFrame(rows)


def _recompute_p_values(table: pl.DataFrame, *, method: str, fisher_backend: str) -> pl.DataFrame:
    """Replace `p_value` with the upper-tail p-value under `method`, validating required columns."""
    observed = _required(table, "observed", method)
    if method == "binomial":
        trials = _required(table, "n_trials", method)
        probability = _required(table, "p_null", method)
        if np.isnan(trials).all():
            raise ValueError(
                "method='binomial' needs n_trials/p_null, which the legacy nine-column output does "
                "not contain. Re-run `touche local-decay call --schema tidy` (or call "
                "`compute_local_decay(..., schema='tidy')`) to produce them."
            )
        p_values = binom_sf_greater(observed, trials, probability)
    elif method == "poisson":
        p_values = poisson_sf_greater(observed, _required(table, "expected", method))
    else:
        expected = _required(table, "expected", method)
        p_values = fisher_greater_batch(
            observed,
            expected,
            _required(table, "observed_background", method),
            _required(table, "expected_background", method),
            backend=fisher_backend,
        )
    return table.with_columns(pl.Series("p_value", p_values))


def _required(table: pl.DataFrame, column: str, method: str) -> np.ndarray:
    """Fetch `column` as a float array, with an error naming the method that needed it."""
    if column not in table.columns:
        raise ValueError(f"method={method!r} requires a {column!r} column")
    return table[column].cast(pl.Float64).to_numpy()


def _calibration_row(p_values: np.ndarray, alpha_levels: tuple[float, ...]) -> dict[str, float | int]:
    """KS-uniformity statistic and empirical rejection rates for one stratum's p-values."""
    from scipy.stats import kstest

    finite = p_values[np.isfinite(p_values)]
    row: dict[str, float | int] = {"n_tested": int(finite.size), "n_input": int(p_values.size)}
    if finite.size < 2:
        row.update(ks_statistic=float("nan"), ks_p_value=float("nan"))
    else:
        result = kstest(finite, "uniform")
        row.update(ks_statistic=float(result.statistic), ks_p_value=float(result.pvalue))
    for alpha in alpha_levels:
        # Anticonservative when this materially exceeds alpha: the test is
        # rejecting more null pairs than its nominal level allows.
        row[f"reject_rate_at_{alpha:g}"] = float(np.mean(finite <= alpha)) if finite.size else float("nan")
    return row
